/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","knockout","ojs/ojknockout","promise"],function(a,g){function c(a,b){var c=null,d=a[b];if(null!=d){c=Object.keys(d)[0];d=d[c];if(null==c)throw"Invalid component descriptor key";switch(c){case "inline":c=Promise.resolve(d);break;case "promise":c=d;break;default:throw"Invalid descriptor key "+c+" for the resopurce type: "+b;}}return c}function b(b,c,d){if(null!=b&&(c=a.qg.Zc[c],null!=c&&b&&(c=b[c],"function"===typeof c)))return g.ignoreDependencies(c,b,d)}function d(a,b,c,d){k(c,
"properties",function(c,e){f(a,b,c,e,d)})}function e(a,b,c){k(b,"methods",function(d){var e=b.methods[d].internalName;a[d]=e?c[e].bind(c):c[d].bind(c)})}function f(a,b,c,d,e){function f(b,d){var g=k.peek();g!==b&&(k(b),!e.WHa()||e.DY())&&(g=new CustomEvent(c+"-changed",{detail:{value:b,previousValue:g,updatedFrom:e.DY()?"default":d?"external":"internal"}}),a.dispatchEvent(g))}var k=g.observable();h(b,c,function(){return k()},function(a){f(a,!1)});h(a,c,function(){return k.peek()},function(a){if(d.readOnly&&
!e.DY())throw"Read-only property "+c+" cannot be set";f(a,!0)})}function h(a,b,c,d){Object.defineProperty(a,b,{configurable:!0,enumerable:!0,get:c,set:d})}function k(a,b,c){if(a){var d=a[b]||{};Object.keys(d).forEach(function(a){c(a,d[a])})}}function l(a,b){["methods","properties"].forEach(function(c){k(b,c,function(b){delete a[b]})})}function m(a){var b={};a=a.childNodes;for(var c=0;c<a.length;c++){var d=a[c];if((1===d.nodeType||3===d.nodeType)&&(3!==d.nodeType||d.nodeValue.trim())){var e=d.__oj_slots;
(e=null!=e?e:d.getAttribute&&d.getAttribute("slot"))||(e="");b[e]||(b[e]=[]);b[e].push(d)}}return b}function r(a,b){var c,d=a.childNodes;if(d){c=document.createElement("div");c.setAttribute("data-bind","_ojNodeStorage_");c.style.display="none";b.push(c);for(var e=[],f=0;f<d.length;f++){var g=d[f];1!==g.nodeType&&3!==g.nodeType||e.push(g)}e.forEach(function(a){c.appendChild(a)})}return c}function t(b,c,d){function e(c,f,g,h,k){!c||h.MZ(g,f,c)||c.readOnly||(g=k?c.value:d?d(g,f,c,function(b){return a.hf.DL(f,
b,c.type)}):a.hf.DL(f,g,c.type),b[f]=g)}this.Nn=function(d){var k=d.properties;if(k){var l=this.esa=new a.U2(b,c);f.setAttribute=b.setAttribute;f.removeAttribute=b.removeAttribute;b.setAttribute=function(a,b){u(a,b,f.setAttribute,!1)};b.removeAttribute=function(a){u(a,null,f.removeAttribute,!0)};var u=function(c,d,f,g){c=c.toLowerCase();var h=b.getAttribute(c);f.apply(b,arguments);var q=b.getAttribute(c);q!==h&&(h=a.hf.iX(c),e(k[h],h,q,l,g))};d=Object.keys(k);g=!0;try{d.forEach(function(c){var d=
a.hf.IA(c),f=b.hasAttribute(d),g=k[c];f&&(d=b.getAttribute(d),e(g,c,d,l,!1));if(!f||g.readOnly)try{h=!0,b[c]=g.value}finally{h=!1}}),b.classList.add("oj-complete")}finally{g=!1}}return this};this.WHa=function(){return g};this.DY=function(){return h};this.KN=function(a){this.esa.KN();var b=Object.keys(f),c;for(c=0;c<b.length;c++){var d=b[c];a[d]=f[d]}f={}};var f={},g,h}(function(){a.qQ.dX({nodeHasBindings:function(b,c){return c||1===b.nodeType&&a.qg.pQ(b.nodeName.toLowerCase())},getBindingAccessors:function(b,
c,d){if(1===b.nodeType&&(b=b.nodeName.toLowerCase(),a.qg.pQ(b))){d=d||{};if(d.ojComposite)throw"Cannot use ojComposite binding on a custom element whose name is already registered for a composite binding";var e={name:b};d.ojComposite=function(){return e}}return d},preprocessNode:function(b,c){var d;if(1===b.nodeType&&"oj-slot"===b.nodeName.toLowerCase()){d=["name","slot","index"];for(var e="ko _ojSlot_:{",f=[],g=0;g<d.length;g++){var h=d[g],k;k=b.getAttribute(h);if(null!=k){var l=a.hf.WE(k).expr;
null==l&&(l="'"+k+"'");k=l}else k=null;k&&f.push(h+":"+k)}e+=f.join(",");g=document.createComment(e+"}");e=document.createComment("/ko");d=[g];f=b.parentNode;for(f.insertBefore(g,b);0<b.childNodes.length;)g=b.childNodes[0],f.insertBefore(g,b),d.push(g);d.push(e);f.replaceChild(e,b)}return d?d:c}})})();a.qg={};a.qg.Zc={initializeMethod:"initialize",activatedMethod:"activated",attachedMethod:"attached",bindingsAppliedMethod:"bindingsApplied",disposeMethod:"dispose"};o_("Composite.defaults",a.qg.Zc,
a);a.qg.register=function(b,c){b&&(a.qg.vK[b.toLowerCase()]=c)};o_("Composite.register",a.qg.register,a);a.qg.pQ=function(b){return b?a.qg.vK[b.toLowerCase()]:null};a.qg.Ana=function(b,c){if(b){var d=a.qg.vK[b.toLowerCase()];d&&(d._metadata=c)}};a.qg.getMetadata=function(b){return b&&(b=a.qg.vK[b.toLowerCase()])?b._metadata:null};o_("Composite.getMetadata",a.qg.getMetadata,a);a.qg.vK={};g.bindingHandlers.ojComposite={init:function(){return{controlsDescendantBindings:!0}},update:function(f,h,k,w,v){function y(a){H&&
(H.KN(f),H=null);I=a;b(C,"disposeMethod",[f]);C=null;E&&l(f,E);A&&(f.removeChild(A),A=null);E=null;G={}}function x(a){return function(b){if(I||b!=K)throw z;return a.apply(this,Array.prototype.slice.call(arguments,1))}.bind(null,K)}var z=Error(),C,H,K=-1,I=!1,E,G={},A,B=g.utils.unwrapObservable;g.ignoreDependencies(function(){g.computed(function(){K++;f.dispatchEvent(new CustomEvent("pending",{bubbles:!0}));y(!1);var k=B(h())||{},k=B(k.name),l=a.qg.pQ(k);if(!l)throw"Composite is missing a descriptor";
var u=c(l,"metadata");a.qg.Ana(k,u);k=null;u?k=u.then(x(function(b){b?(E=b,H=new t(f,v,l.parseFunction),d(f,G,b,H),H.Nn(b)):(f.classList.add("oj-complete"),a.r.warn("ojComposite is being loaded without metadata. No element properties will be set up"));return G})):f.classList.add("oj-complete");var w,u=new Promise(function(a){w=a}),N=n+s++,M={element:f,props:k,slotNodeCounts:u,unique:N},u=null,Q=c(l,"viewModel");Q&&(u=Q.then(x(function(a){return a="function"===typeof a?new a(M):b(a,"initializeMethod",
[M])||a})));Q=null;u&&(Q=u.then(x(function(a){return b(a,"activatedMethod",[M])})));var O=c(l,"view");O&&(O=O.then(x(function(a){if("string"===typeof a)a=g.utils.parseHtmlFragment(a);else if(window.DocumentFragment?a instanceof DocumentFragment:a&&11===a.nodeType)a=g.utils.arrayPushAll([],a.childNodes);else if(Array.isArray(a))a=g.utils.arrayPushAll([],a);else throw"The View ("+a+") has an unsupported type";return a})));var S=c(l,"css");S&&(S=S.then(x(function(a){var b=document.createElement("style");
b.type="text/css";b.styleSheet?b.styleSheet.cssText=a:b.appendChild(document.createTextNode(a));document.head.appendChild(b)})));g.applyBindingsToDescendants(v,f);Promise.all([O,u,k,S,Q]).then(function(a,c){if(!I&&a==K){var d=c[0];if(!d)throw"ojComposite is missing a View";var h=m(f),k={},q;for(q in h)k[q]=h[q].length;w(k);A=r(f,d);g.virtualElements.setDomNodeChildren(f,d);C=c[1];b(C,"attachedMethod",[M]);d=v.createChildContext(C,void 0,function(a){a.__oj_slots=h;a.__oj_nodestorage=A;a.$slotNodeCounts=
k;a.$props=G;a.$unique=N});E&&C&&e(f,E,C);g.applyBindingsToDescendants(d,f);b(C,"bindingsAppliedMethod",[M]);f.dispatchEvent(new CustomEvent("ready",{bubbles:!0}))}}.bind(null,K),function(b,c){c!==z&&null!=c&&a.r.error(c)}.bind(null,K))},null,{disposeWhenNodeIsRemoved:f})});g.utils.domNodeDisposal.addDisposeCallback(f,y.bind(null,!0,v))}};var s=0,n="_ojcomposite";g.bindingHandlers._ojNodeStorage_={init:function(){return{controlsDescendantBindings:!0}}};g.bindingHandlers._ojSlot_={init:function(a,
b,c,d,e){g.utils.domNodeDisposal.addDisposeCallback(a,function(b){if(b=b.__oj_nodestorage)for(var c;c=g.virtualElements.firstChild(a);)null!=c.__oj_slots&&b.appendChild(c)}.bind(null,e));d=e.__oj_slots;b=b();c=g.utils.unwrapObservable;e=c(b.name)||"";var f=c(b.index);if(d=null!=f?[d[e][f]]:d[e]){for(e=0;e<d.length;e++)d[e].__oj_slots=c(b.slot)||"";g.virtualElements.setDomNodeChildren(a,d);return{controlsDescendantBindings:!0}}}};g.virtualElements.allowedBindings._ojSlot_=!0});